version: '3'
services:
    test:
        build: ./test
        image: test:1.0
        #dockerfile: /test/Dockerfile
        container_name: "test"
        environment:
            - FOO=bar
        volumes:
            - /Users/mmanning/Dev/code/gtt/test/:/code/test/:rw
        ports:
            - 3000:3000
            - 9000:9000
        links:
            - mongodb
        depends_on:
            - mongodb
            - pgdb
    
    mongodb:
        restart: always
        image: bitnami/mongodb:latest
        container_name: "mongodb"
        environment:
            - MONGODB_USERNAME=gtt
            - MONGODB_PASSWORD=gtt123
            - MONGODB_DATABASE=ingestdb
        volumes:
            - /Users/mmanning/Dev/data/mongodb:/bitnami
        ports:
            - 27017:27017
        
    pgdb:
        # https://github.com/bitnami/bitnami-docker-postgresql
        restart: always
        image: 'bitnami/postgresql:latest'
        container_name: "pgdb"
        ports:
            - "5432:5432"
        environment:
            - POSTGRESQL_USERNAME=gtt
            - POSTGRESQL_PASSWORD=password123
            - MONGODB_ROOT_PASSWORD=password123
            - POSTGRESQL_DATABASE=accounts

        volumes:
            - /Users/mmanning/Dev/data/postgres:/var/lib/postgresql        
        
